BEGIN;

CREATE TABLE IF NOT EXISTS entidades_fiscales (
    id_entidad BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_entidad TEXT NOT NULL CHECK (tipo_entidad IN ('empresa', 'emisor', 'receptor', 'mixta')),
    rfc TEXT NOT NULL UNIQUE,
    razon_social TEXT NOT NULL,
    nombre_comercial TEXT,
    tipo_persona TEXT CHECK (tipo_persona IN ('fisica', 'moral')),
    regimen_fiscal TEXT,
    codigo_postal_fiscal TEXT NOT NULL,
    correo_fiscal TEXT,
    correo_comercial TEXT,
    telefono TEXT,
    sector TEXT,
    activo SMALLINT NOT NULL DEFAULT 1 CHECK (activo IN (0, 1)),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS domicilios_fiscales (
    id_domicilio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entidad BIGINT NOT NULL REFERENCES entidades_fiscales(id_entidad),
    calle TEXT,
    numero_exterior TEXT,
    numero_interior TEXT,
    colonia TEXT,
    municipio TEXT,
    estado TEXT,
    pais TEXT NOT NULL DEFAULT 'MEX',
    codigo_postal TEXT NOT NULL,
    referencia TEXT,
    es_fiscal_principal SMALLINT NOT NULL DEFAULT 1 CHECK (es_fiscal_principal IN (0, 1)),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS contactos (
    id_contacto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entidad BIGINT NOT NULL REFERENCES entidades_fiscales(id_entidad),
    nombre TEXT NOT NULL,
    correo TEXT,
    telefono TEXT,
    puesto TEXT,
    es_contacto_cfdi SMALLINT NOT NULL DEFAULT 0 CHECK (es_contacto_cfdi IN (0, 1)),
    activo SMALLINT NOT NULL DEFAULT 1 CHECK (activo IN (0, 1)),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS prospectos (
    id_prospecto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entidad BIGINT NOT NULL UNIQUE REFERENCES entidades_fiscales(id_entidad),
    id_contacto BIGINT REFERENCES contactos(id_contacto),
    origen TEXT,
    fuente TEXT,
    estado TEXT NOT NULL CHECK (estado IN ('nuevo', 'contactado', 'calificado', 'perdido', 'convertido')),
    es_cliente SMALLINT NOT NULL DEFAULT 0 CHECK (es_cliente IN (0, 1)),
    fecha_conversion_cliente TIMESTAMPTZ,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS oportunidades (
    id_oportunidad BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entidad BIGINT NOT NULL REFERENCES entidades_fiscales(id_entidad),
    id_prospecto BIGINT REFERENCES prospectos(id_prospecto),
    folio_oportunidad TEXT UNIQUE,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    etapa TEXT NOT NULL CHECK (etapa IN ('calificacion', 'negociacion', 'propuesta', 'cierre', 'postventa')),
    estado TEXT NOT NULL CHECK (estado IN ('abierta', 'ganada', 'perdida', 'cancelada')),
    probabilidad INTEGER NOT NULL DEFAULT 0 CHECK (probabilidad >= 0 AND probabilidad <= 100),
    monto_estimado NUMERIC(18,2) NOT NULL DEFAULT 0,
    moneda_estimacion TEXT NOT NULL DEFAULT 'MXN',
    fecha_estimada_cierre TIMESTAMPTZ,
    oc_recibida SMALLINT NOT NULL DEFAULT 0 CHECK (oc_recibida IN (0, 1)),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS cotizaciones (
    id_cotizacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_oportunidad BIGINT NOT NULL REFERENCES oportunidades(id_oportunidad),
    folio_cotizacion TEXT NOT NULL UNIQUE,
    version INTEGER NOT NULL DEFAULT 1,
    modo TEXT NOT NULL CHECK (modo IN ('minimo', 'generico', 'externo')),
    fuente TEXT,
    moneda TEXT NOT NULL DEFAULT 'MXN',
    subtotal NUMERIC(18,2) NOT NULL DEFAULT 0,
    descuento NUMERIC(18,2) NOT NULL DEFAULT 0,
    impuestos_trasladados NUMERIC(18,2) NOT NULL DEFAULT 0,
    impuestos_retenidos NUMERIC(18,2) NOT NULL DEFAULT 0,
    total NUMERIC(18,2) NOT NULL,
    estado TEXT NOT NULL CHECK (estado IN ('borrador', 'enviada', 'aceptada', 'rechazada', 'vencida')),
    notas TEXT,
    fecha_emision TIMESTAMPTZ NOT NULL,
    fecha_vigencia TIMESTAMPTZ,
    hash_integridad TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS ordenes_compra (
    id_oc BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entidad BIGINT NOT NULL REFERENCES entidades_fiscales(id_entidad),
    id_oportunidad BIGINT NOT NULL REFERENCES oportunidades(id_oportunidad),
    numero_oc TEXT NOT NULL UNIQUE,
    fecha_oc TIMESTAMPTZ NOT NULL,
    moneda TEXT NOT NULL DEFAULT 'MXN',
    subtotal NUMERIC(18,2) NOT NULL DEFAULT 0,
    total NUMERIC(18,2) NOT NULL,
    archivo_pdf TEXT,
    estado TEXT NOT NULL CHECK (estado IN ('pendiente', 'parcial', 'facturada', 'cancelada')),
    hash_integridad TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS comprobantes_cfdi (
    id_cfdi BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid TEXT NOT NULL UNIQUE,
    id_emisor BIGINT NOT NULL REFERENCES entidades_fiscales(id_entidad),
    id_receptor BIGINT NOT NULL REFERENCES entidades_fiscales(id_entidad),
    id_oc BIGINT REFERENCES ordenes_compra(id_oc),
    version_cfdi TEXT NOT NULL DEFAULT '4.0',
    tipo_comprobante TEXT NOT NULL CHECK (tipo_comprobante IN ('I', 'E', 'P', 'T', 'N')),
    exportacion TEXT DEFAULT '01',
    serie TEXT,
    folio TEXT,
    fecha_emision TIMESTAMPTZ NOT NULL,
    fecha_timbrado TIMESTAMPTZ,
    moneda TEXT NOT NULL DEFAULT 'MXN',
    forma_pago TEXT,
    metodo_pago TEXT,
    uso_cfdi TEXT,
    subtotal NUMERIC(18,2) NOT NULL,
    descuento NUMERIC(18,2) NOT NULL DEFAULT 0,
    total_trasladados NUMERIC(18,2) NOT NULL DEFAULT 0,
    total_retenidos NUMERIC(18,2) NOT NULL DEFAULT 0,
    total NUMERIC(18,2) NOT NULL,
    estado TEXT NOT NULL CHECK (estado IN ('borrador', 'timbrado', 'cancelado', 'pagado', 'error')),
    xml_path TEXT,
    pdf_path TEXT,
    hash_integridad TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS conceptos_cfdi (
    id_concepto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cfdi BIGINT NOT NULL REFERENCES comprobantes_cfdi(id_cfdi),
    clave_prod_serv TEXT NOT NULL,
    no_identificacion TEXT,
    cantidad NUMERIC(18,6) NOT NULL,
    clave_unidad TEXT NOT NULL,
    unidad TEXT,
    descripcion TEXT NOT NULL,
    valor_unitario NUMERIC(18,6) NOT NULL,
    importe NUMERIC(18,2) NOT NULL,
    descuento NUMERIC(18,2) NOT NULL DEFAULT 0,
    objeto_imp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS impuestos_cfdi (
    id_impuesto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cfdi BIGINT REFERENCES comprobantes_cfdi(id_cfdi),
    id_concepto BIGINT REFERENCES conceptos_cfdi(id_concepto),
    tipo TEXT NOT NULL CHECK (tipo IN ('traslado', 'retencion')),
    impuesto TEXT NOT NULL,
    tipo_factor TEXT NOT NULL CHECK (tipo_factor IN ('Tasa', 'Cuota', 'Exento')),
    tasa_o_cuota NUMERIC(18,6),
    base NUMERIC(18,2) NOT NULL,
    importe NUMERIC(18,2)
);

CREATE TABLE IF NOT EXISTS pagos_cfdi (
    id_pago BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cfdi BIGINT NOT NULL REFERENCES comprobantes_cfdi(id_cfdi),
    folio_pago TEXT,
    fecha_pago TIMESTAMPTZ NOT NULL,
    forma_pago TEXT NOT NULL,
    moneda_pago TEXT NOT NULL,
    monto NUMERIC(18,2) NOT NULL,
    num_operacion TEXT,
    referencia TEXT,
    estado TEXT NOT NULL CHECK (estado IN ('registrado', 'conciliado', 'cancelado')),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS xml_documentos (
    id_xml BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cfdi BIGINT NOT NULL REFERENCES comprobantes_cfdi(id_cfdi),
    version_cfdi TEXT NOT NULL,
    xml_raw TEXT,
    xml_path TEXT,
    hash_xml TEXT NOT NULL UNIQUE,
    origen TEXT NOT NULL CHECK (origen IN ('emitido', 'recibido', 'digerido')),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS certificados_csd (
    id_certificado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entidad BIGINT NOT NULL REFERENCES entidades_fiscales(id_entidad),
    numero_certificado TEXT,
    cer_base64 TEXT NOT NULL,
    key_base64 TEXT NOT NULL,
    fecha_inicio_vigencia TIMESTAMPTZ,
    fecha_fin_vigencia TIMESTAMPTZ,
    activo SMALLINT NOT NULL DEFAULT 1 CHECK (activo IN (0, 1)),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS eventos_auditoria (
    id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad_tipo TEXT NOT NULL,
    entidad_id BIGINT NOT NULL,
    accion TEXT NOT NULL,
    valor_anterior TEXT,
    valor_nuevo TEXT,
    usuario TEXT,
    timestamp_evento TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    hash_evento TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS hashes_integridad (
    id_hash BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_origen TEXT NOT NULL,
    id_registro BIGINT NOT NULL,
    hash_sha256 TEXT NOT NULL,
    timestamp_hash TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS relaciones_grafo (
    id_relacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nodo_origen_tipo TEXT NOT NULL,
    nodo_origen_id BIGINT NOT NULL,
    tipo_relacion TEXT NOT NULL,
    nodo_destino_tipo TEXT NOT NULL,
    nodo_destino_id BIGINT NOT NULL,
    vigente SMALLINT NOT NULL DEFAULT 1 CHECK (vigente IN (0, 1)),
    metadata_json TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_entidades_fiscales_rfc ON entidades_fiscales(rfc);
CREATE INDEX IF NOT EXISTS idx_contactos_entidad ON contactos(id_entidad);
CREATE INDEX IF NOT EXISTS idx_prospectos_entidad ON prospectos(id_entidad);
CREATE INDEX IF NOT EXISTS idx_oportunidades_entidad ON oportunidades(id_entidad);
CREATE INDEX IF NOT EXISTS idx_oportunidades_prospecto ON oportunidades(id_prospecto);
CREATE INDEX IF NOT EXISTS idx_cotizaciones_oportunidad ON cotizaciones(id_oportunidad);
CREATE INDEX IF NOT EXISTS idx_ordenes_compra_entidad ON ordenes_compra(id_entidad);
CREATE INDEX IF NOT EXISTS idx_ordenes_compra_oportunidad ON ordenes_compra(id_oportunidad);
CREATE INDEX IF NOT EXISTS idx_comprobantes_cfdi_uuid ON comprobantes_cfdi(uuid);
CREATE INDEX IF NOT EXISTS idx_comprobantes_cfdi_emisor ON comprobantes_cfdi(id_emisor);
CREATE INDEX IF NOT EXISTS idx_comprobantes_cfdi_receptor ON comprobantes_cfdi(id_receptor);
CREATE INDEX IF NOT EXISTS idx_comprobantes_cfdi_oc ON comprobantes_cfdi(id_oc);
CREATE INDEX IF NOT EXISTS idx_conceptos_cfdi_cfdi ON conceptos_cfdi(id_cfdi);
CREATE INDEX IF NOT EXISTS idx_impuestos_cfdi_cfdi ON impuestos_cfdi(id_cfdi);
CREATE INDEX IF NOT EXISTS idx_impuestos_cfdi_concepto ON impuestos_cfdi(id_concepto);
CREATE INDEX IF NOT EXISTS idx_pagos_cfdi_cfdi ON pagos_cfdi(id_cfdi);
CREATE INDEX IF NOT EXISTS idx_xml_documentos_cfdi ON xml_documentos(id_cfdi);
CREATE INDEX IF NOT EXISTS idx_xml_documentos_hash ON xml_documentos(hash_xml);
CREATE INDEX IF NOT EXISTS idx_certificados_csd_entidad ON certificados_csd(id_entidad);
CREATE INDEX IF NOT EXISTS idx_eventos_auditoria_entidad ON eventos_auditoria(entidad_tipo, entidad_id);
CREATE INDEX IF NOT EXISTS idx_hashes_integridad_origen ON hashes_integridad(tabla_origen, id_registro);
CREATE INDEX IF NOT EXISTS idx_relaciones_grafo_origen ON relaciones_grafo(nodo_origen_tipo, nodo_origen_id);
CREATE INDEX IF NOT EXISTS idx_relaciones_grafo_destino ON relaciones_grafo(nodo_destino_tipo, nodo_destino_id);
CREATE INDEX IF NOT EXISTS idx_relaciones_grafo_tipo ON relaciones_grafo(tipo_relacion);

COMMIT;